Youtube Channel Name 🎥 : BroCode 👨🏻‍💻

Video 🎥 URL : https://youtu.be/VXU4LSAQDSc?list=PLZPZq0r_RZOO_wKfxdnAb9BgnffGtIHjR

What is NumPy ? 

NumPy = Numerical Python

NumPy is an one of the python libraries that is used for numerical calculations.

1-) Introduction to NumPy

In [16]:
import numpy as np

In [17]:
print(np.__version__)

2.4.0


In [18]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [19]:
my_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
array = np.array([1,2,3,4])

In [21]:
array

array([1, 2, 3, 4])

In [22]:
type(array)

numpy.ndarray

In [23]:
array = array * 2
array

array([2, 4, 6, 8])

Multidimensional Arrays

In [24]:
import numpy as np

In [25]:
array = np.array(['A','B','C'])
array.ndim

1

In [27]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array.ndim

2

In [28]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.ndim

3

In [32]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.shape

(3, 3, 3)

In [33]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.shape

(2, 3, 3)

In [34]:
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
array[0][0][0]

np.int64(1)

In [50]:
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','A']]])
print(array)

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' 'A']]]


In [51]:
print(array[0,0,0])

A


In [52]:
print(array[0,0,1])

B


In [53]:
print(array[0,1,1])

E
