Youtube Channel Name 🎥 : BroCode 👨🏻‍💻

Video 🎥 URL : https://youtu.be/VXU4LSAQDSc?list=PLZPZq0r_RZOO_wKfxdnAb9BgnffGtIHjR

What is NumPy ? 

NumPy = Numerical Python

NumPy is an one of the python libraries that is used for numerical calculations.

1-) Introduction to NumPy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.0


In [3]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [4]:
my_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
array = np.array([1,2,3,4])

In [6]:
array

array([1, 2, 3, 4])

In [7]:
type(array)

numpy.ndarray

In [8]:
array = array * 2
array

array([2, 4, 6, 8])

Multidimensional Arrays

In [9]:
import numpy as np

In [10]:
array = np.array(['A','B','C'])
array.ndim

1

In [11]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array.ndim

2

In [12]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.ndim

3

In [13]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.shape

(3, 3, 3)

In [14]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array.shape

(2, 3, 3)

In [15]:
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
array[0][0][0]

np.int64(1)

In [18]:
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','A']]])
print(array)

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' 'A']]]


In [19]:
print(array[0,0,0])

A


In [20]:
print(array[0,0,1])

B


In [21]:
print(array[0,1,1])

E


In [22]:
word = array[0,0,1] + array[2,2,0] + array[2,0,1] + "23"
word

'BYT23'

Slicing ✂️

In [23]:
import numpy as np

In [24]:
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

array[start:stop:step]

In [25]:
print(array[0])
print(array[1])
print(array[2])
print(array[3])
print(array[-1])
print(array[-2])
print(array[-3])
print(array[-4])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[13 14 15 16]
[ 9 10 11 12]
[5 6 7 8]
[1 2 3 4]


In [26]:
print(array[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [28]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [29]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [30]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
print(array[:,3])

[ 4  8 12 16]


In [32]:
print(array[:,-2])

[ 3  7 11 15]


In [33]:
print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [34]:
print(array[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


Arithmetic 🧮

Scalar Arithmetic

In [35]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [36]:
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


Vectorized Math Functions

In [37]:
import numpy as np

In [38]:
array

array([1, 2, 3])

In [39]:
array = np.array([1,2,3])
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [40]:
array = np.array([1.01, 2.5, 3.99])
print(np.round(array))

[1. 2. 4.]


In [41]:
array = np.array([1.01, 2.5, 3.99])
print(np.ceil(array))

[2. 3. 4.]


In [42]:
array = np.array([1.01, 2.5, 3.99])
print(np.floor(array))

[1. 2. 3.]


In [43]:
array = np.array([1.01, 2.5, 3.99])
print(np.ceil(array))

[2. 3. 4.]


In [44]:
print(np.pi)

3.141592653589793


In [45]:
# 2nd way to import pi
import math

pi = math.pi
print(pi)

3.141592653589793


In [46]:
radii = np.array([1,2,3])

In [47]:
radii

array([1, 2, 3])

In [48]:
# Example: Area of circles with the given radii

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [49]:
# Element - wise arithmetic operations are possible with NumPy arrays.

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


Comparison Operators

In [50]:
scores = np.array([91,55,100,73,82,64])

In [51]:
print(scores == 100)

[False False  True False False False]


In [52]:
print(scores < 60)

[False  True False False False False]


In [53]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


Broadcasting

a(4x3) + b(1x3) = result(4x3)

In [54]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

In [55]:
print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [56]:
print(array1 * array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [57]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])
array2 = np.array([[1],[2],[3],[4]])

In [58]:
print(array1 * array2)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [59]:
array1.shape

(4, 4)

In [60]:
array2.shape

(4, 1)

In [61]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

In [62]:
print(array1.shape)
print(array2.shape)

(1, 10)
(10, 1)


In [63]:
print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Aggregate Functions

Summarize data amd typically return a single value

In [64]:
import numpy as np

In [65]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array)) # sum is the total of all the numbers in the array
print(np.mean(array))# mean is the average of the numbers in the array
print(np.min(array)) # minimum
print(np.max(array)) # maximum
print(np.std(array)) # standard deviation
print(np.var(array)) # variance
print(np.sqrt(array)) # square root of each element in the array
print(np.argmin(array)) # index of the minimum element in the array
print(np.argmax(array)) # index of the maximum element in the array

55
5.5
1
10
2.8722813232690143
8.25
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
0
9


In [66]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(array, axis=0)) # sum of each column
print(np.sum(array, axis=1)) # sum of each row

[ 7  9 11 13 15]
[15 40]


Filtering ⚖️

Refers to the process of selecting elements from an array that match a given condition

In [67]:
import numpy as np

In [68]:
ages = np.array([[21,17,19,20,16,30,18,65], 
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18]
print(teenagers)

[17 16 15]


In [69]:
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [70]:
seniors = ages[ages >= 65]
print(seniors)

[65 99]


In [71]:
evens = ages[ages % 2 == 0]
print(evens)

[20 16 30 18 22 18 20]


In [72]:
odds = ages[ages % 2 == 1]
print(odds)

[21 17 19 65 39 15 99 19 21]


In [73]:
adults = np.where(ages >= 18, ages, 0)
print(adults)

# The np.where() function is used to create a new array based on a condition. 
# In this case, it checks if each element in the 'ages' array is greater than or equal to 18.
# If the condition is true, it keeps the original age; if false, it replaces it with 0.

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


Random Numbers 🔢 🧮

In [74]:
import numpy as np

rng = np.random.default_rng()
print(rng.integers(1, 7)) # The integers() method generates random integers from a specified range.

3


In [75]:
print(rng.integers(low=70, high=170)) 
# The low parameter is inclusive, while the high parameter is exclusive.

122


In [76]:
print(rng.integers(low=150, high=300, size = 5)) 
# The size parameter specifies the number of random integers to generate.
# In this case, it will generate an array of 5 random integers between 150 (inclusive) and 300 (exclusive).

[154 199 245 250 150]


In [77]:
print(rng.integers(low=150, high=300, size = (3,2))) 

[[180 267]
 [263 281]
 [225 151]]


In [78]:
rng = np.random.default_rng(seed=1) # Setting a seed for reproducibility
print(rng.integers(low=150, high=300, size = (3,2))) 
# The same random integers will be generated every time the code is run, due to the fixed seed.

[[220 226]
 [263 292]
 [155 171]]


In [79]:
# Uniform distribution generates random numbers between a specified range with equal probability.

import numpy as np

print(np.random.uniform(low = -1, high= 1, size = 4))

[-0.4579625   0.72344761  0.59451062  0.15694178]


In [80]:
print(np.random.uniform(low = -1, high= 1, size = (4,5)))

[[ 0.52805663  0.38762904  0.21069666 -0.25502461 -0.61723227]
 [-0.84735071 -0.44241401  0.13766877 -0.26670375 -0.63643774]
 [ 0.07613569 -0.7479149   0.46426421 -0.71158952 -0.69397886]
 [ 0.96293655 -0.84054357 -0.37629431 -0.64583919  0.52901608]]


In [81]:
np.random.seed(seed = 1)
print(np.random.uniform(low = -1, high= 1, size = (4,5)))

[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]
 [ 0.34093502 -0.1653904   0.11737966 -0.71922612 -0.60379702]]


In [82]:
import numpy as np

rng = np.random.default_rng() # Create a random number generator with a seed for reproducibility

array = np.array([1,2,3,4,5])

rng.shuffle(array) # Shuffle the elements of the array in place
print(array)

[2 4 1 3 5]


In [83]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(fruits)

['apple' 'banana' 'cherry' 'date' 'elderberry']


In [84]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(['apple', 'banana', 'cherry', 'strawberry', 'elderberry'])
fruits = rng.choice(fruits)
print(fruits)

apple


In [85]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(['apple', 'banana', 'cherry', 'orange', 'elderberry'])
fruits = rng.choice(fruits, size=3)
print(fruits)

['banana' 'orange' 'elderberry']


In [86]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(['apple', 'banana', 'cherry', 'strawberry', 'elderberry'])
fruits = rng.choice(fruits, size = (3,3))
print(fruits)

[['elderberry' 'cherry' 'apple']
 ['strawberry' 'elderberry' 'apple']
 ['banana' 'strawberry' 'strawberry']]


The End...