In [3]:
import numpy as np

In [4]:
my_list = [1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

np.int64(5)

In [10]:
print(my_numpy_array.max())

5


In [11]:
print(my_numpy_array.mean())

3.0


In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.random.random(5)

array([0.00622006, 0.45783901, 0.67689858, 0.69363744, 0.94730215])

Array Arithmetic

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 = np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [21]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [22]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [23]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [24]:
my_numpy_array1 * 5

array([ 5, 10])

In [25]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [26]:
other_array = np.array([10,20,30,40,50])

In [27]:
other_array.min()

np.int64(10)

In [28]:
other_array.sum()

np.int64(150)

In [29]:
my_numpy_array1

array([1, 2])

In [30]:
other_array

array([10, 20, 30, 40, 50])