ATIL SAMANCIOĞLU'S DATA SCIENCE AND MACHINE LEARNING  COURSE - NUMPY LIBRARY 

A Visual 📊 Intro to NumPy 🧮 and Data Representation 📈 📉 by Jay Alammar 

Link : https://jalammar.github.io/visual-numpy/

1-) NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
my_numpy_array = np.array(my_list)

In [5]:
type(my_numpy_array)

numpy.ndarray

In [6]:
my_numpy_array.max()

np.int64(40)

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.random.random(5)

array([0.38146347, 0.32457663, 0.77932151, 0.68949309, 0.77604224])

Array Arithmetic

In [10]:
my_list1 = [1,2]

In [11]:
my_list2 = [2,3]

In [12]:
my_list1 + my_list2

[1, 2, 2, 3]

In [13]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)

In [14]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [15]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [16]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [17]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [18]:
my_numpy_array1

array([1, 2])

In [19]:
my_numpy_array1 * 5

array([ 5, 10])

In [20]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [21]:
other_array = np.array([10,20,30,40,50])

In [22]:
other_array.max()

np.int64(50)

In [23]:
other_array.min()

np.int64(10)

In [24]:
other_array.sum()

np.int64(150)

In [25]:
other_array

array([10, 20, 30, 40, 50])

Index Operations in NumPy

arange & indexing

In [26]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np_array = np.array(np.arange(0,10))

In [30]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np_array[0]

np.int64(0)

In [32]:
np_array[-1]

np.int64(9)

In [33]:
np_array[1:4:]

array([1, 2, 3])

In [34]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
np_array[2:6:2]

array([2, 4])

Random

In [36]:
np.random.randn(4)

array([ 0.11844263, -2.8536935 , -0.1658068 ,  0.05429982])

In [37]:
np.random.rand(4)

array([0.64264099, 0.71288294, 0.00326709, 0.46006528])

In [38]:
np.random.randn(4,4)

array([[ 0.61939944, -2.68570194,  0.79218846, -0.91593955],
       [ 0.04523114, -1.9213228 , -1.37316606,  0.26931695],
       [-1.22295961,  0.72894087, -2.36308025,  0.05959439],
       [-0.72111307, -1.02202031,  0.94503956, -0.55347556]])

In [39]:
np.random.randint(1,300,5)

array([173, 196, 212, 130, 144])

Matrices in NumPy

In [40]:
import numpy as np

In [41]:
my_matrix = [[5,10],[15,20]]

In [42]:
my_matrix[0]

[5, 10]

In [43]:
my_matrix[1]

[15, 20]

In [44]:
my_matrix[0][1]

10

In [45]:
my_matrix[1][0]

15

In [46]:
# row * column

In [47]:
numpy_matrix = np.array([[5,10],[15,20]])

In [48]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [49]:
numpy_matrix[1][0]

np.int64(15)

In [50]:
numpy_matrix.sum()

np.int64(50)

In [51]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.random.random((3,2))

array([[0.52799685, 0.71686147],
       [0.4655381 , 0.07897267],
       [0.95186944, 0.6262267 ]])

Matrix Arithmetic

In [54]:
first_array = np.array([[10,20],[30,40]])

In [55]:
second_array = np.array([[5,15],[25,35]])

In [56]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [57]:
first_array

array([[10, 20],
       [30, 40]])

In [58]:
third_array = np.array([[50,60]])

In [59]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [60]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [61]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [62]:
third_array = np.array([[10],[20]])

In [63]:
third_array

array([[10],
       [20]])

In [64]:
third_array.shape

(2, 1)

In [65]:
first_array.shape

(2, 2)

In [66]:
first_array

array([[10, 20],
       [30, 40]])

In [67]:
first_array + third_array

array([[20, 30],
       [50, 60]])

Matrix Multiplication ✖️

In [68]:
first_array

array([[10, 20],
       [30, 40]])

In [69]:
second_array

array([[ 5, 15],
       [25, 35]])

In [70]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [71]:
# dot product
# 1x2 * 2x2 = 1x2 , 3x5 * 5x2 = 3x2 , ... etc.

In [72]:
first_matrix = np.array([[10,20,30]])

In [73]:
first_matrix

array([[10, 20, 30]])

In [74]:
first_matrix.shape

(1, 3)

In [75]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [76]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [77]:
second_matrix.shape

(3, 2)

In [78]:
# first_matrix * second_matrix

In [79]:
result_matrix = np.dot(first_matrix,second_matrix)

In [80]:
result_matrix

array([[120, 180]])

In [81]:
result_matrix = first_matrix.dot(second_matrix)

In [82]:
result_matrix

array([[120, 180]])

In [83]:
result_matrix.shape

(1, 2)

The Last Dance

In [84]:
import numpy as np

In [85]:
new_array = np.random.randint(1,100,20)

In [86]:
new_array

array([ 6, 34, 77, 87, 28, 30, 64, 56, 62, 94, 37, 92, 11, 97, 49, 26, 73,
       50, 10, 67])

In [87]:
new_array > 25 

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True])

In [88]:
new_array[new_array > 25]

array([34, 77, 87, 28, 30, 64, 56, 62, 94, 37, 92, 97, 49, 26, 73, 50, 67])

In [89]:
new_array[new_array < 25]

array([ 6, 11, 10])

transpose & reshape

In [90]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [91]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [92]:
matrix_array.shape

(3, 2)

In [93]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [94]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [95]:
random_array = np.random.rand(6,1)

In [96]:
random_array

array([[0.00391667],
       [0.14303914],
       [0.40063549],
       [0.05699653],
       [0.83203077],
       [0.31067438]])

In [97]:
random_array.shape

(6, 1)

In [98]:
random_array.reshape(2,3)

array([[0.00391667, 0.14303914, 0.40063549],
       [0.05699653, 0.83203077, 0.31067438]])

In [99]:
random_array.reshape(3,2)

array([[0.00391667, 0.14303914],
       [0.40063549, 0.05699653],
       [0.83203077, 0.31067438]])

z-score = (x - mean) / std

In [100]:
data = np.array([10,12,13,15,18,25,100,105])

In [101]:
# Outliers are data points that are significantly different from the rest of the data. 
# They can be identified using z-scores, which measure how many standard deviations a data point is from the mean. 
# A common threshold for identifying outliers is a z-score of 3 or -3,
# Meaning that any data point with a z-score greater than 3 or less than -3 is considered an outlier.

In [102]:
mean = np.mean(data)
mean

np.float64(37.25)

In [103]:
data.sum() / len(data)

np.float64(37.25)

In [104]:
std = np.std(data)
std

np.float64(37.9333296719389)

In [105]:
z_scores = (data - mean) / std
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [106]:
data[z_scores > 1]

array([100, 105])

Math Equations

2x + 3y = 8 and 5x + 7y = 19

Coefficient

In [107]:
A = np.array([[2,3],[5,7]])

Constant

In [108]:
b = np.array([8,19])

In [109]:
solution = np.linalg.solve(A,b)
solution

array([1., 2.])

The End...