In [42]:
import numpy as np

Numpy ➕,➖ Tutorial 👨🏻‍💻/👩🏻‍💻 --> https://www.w3schools.com/python/numpy/default.asp

In [43]:
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1)

[1 2 3 4 5]


Checking Numpy Version

In [44]:
print(np.__version__)

2.4.0


Create a Numpy ndarray Object

In [45]:
array_2 = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

print(array_2)
print(type(array_2))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


Using Tuple to Create a Numpy Array 

In [46]:
array_3 = np.array((1, 2, 3, 4, 5))
print(array_3)

[1 2 3 4 5]


In [47]:
# 0-D array
array_4 = np.array(42)
print(array_4)

42


In [48]:
# 1-D array
array_5 = np.array([1, 2, 3, 4, 5])
print(array_5)

[1 2 3 4 5]


In [49]:
# 2-D array
array_6 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_6)

[[1 2 3]
 [4 5 6]]


In [50]:
# 3-D array
array_7 = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[7, 8, 9], [10, 11, 12],[13, 14, 15]], [[13, 14, 15], [16, 17, 18],[19, 20, 21]]])
print(array_7)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]]]


In [51]:
# ndim attribute

import numpy as np

a = np.array(94)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimeonsional Arrays

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


Access Array Elements

In [53]:
import numpy as np

In [54]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [55]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [56]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


Accessing 2-D Arrays

In [57]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [58]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd dim :' ,arr[1, 4])

5th element on 2nd dim : 10


In [59]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Negative Indexing

In [60]:
import numpy as np

In [61]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim :', arr[1, -1])

Last element from 2nd dim : 10


Array Slicing

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [64]:
import numpy as np

array_e = np.array([1, 2, 3, 4, 5, 6, 7])

print(array_e[4:])

[5 6 7]


In [65]:
import numpy as np

array_f = np.array([1,2,3,4,5,6,7,8,9,10])

print(array_f[:4])

[1 2 3 4]


Negative Slicing

In [67]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-3:-1])

[8 9]


Slicing and Indexing with Step

In [71]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

print(arr[0:19:3])


[ 1  4  7 10 13 16 19]


Slicing 2-D Arrays

In [72]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


NUMPY DATA TYPES

- Data Types in Python
    - Strings
    - Integer
    - Float
    - Boolean
    - Complex

Data Types in Numpy

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

Checking the Data Type of an Array

In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [77]:
import numpy as np

arr = np.array(["apple", "banana", "cherry"])

print(arr.dtype)

<U6


Creating Arrays With a Defined Data Type

In [79]:
import numpy as np

arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [82]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Numpy Array Copy vs View

In [83]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base attribute refers to the original object.

That's why; The copy returns None.,The view returns the original array.

In [85]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


Numpy Array Shape