In [20]:
import numpy as np

In [21]:
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1)

[1 2 3 4 5]


Checking Numpy Version

In [22]:
print(np.__version__)

2.4.0


Create a Numpy ndarray Object

In [23]:
array_2 = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

print(array_2)
print(type(array_2))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


Using Tuple to Create a Numpy Array 

In [24]:
array_3 = np.array((1, 2, 3, 4, 5))
print(array_3)

[1 2 3 4 5]


In [25]:
# 0-D array
array_4 = np.array(42)
print(array_4)

42


In [26]:
# 1-D array
array_5 = np.array([1, 2, 3, 4, 5])
print(array_5)

[1 2 3 4 5]


In [27]:
# 2-D array
array_6 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_6)

[[1 2 3]
 [4 5 6]]


In [28]:
# 3-D array
array_7 = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[7, 8, 9], [10, 11, 12],[13, 14, 15]], [[13, 14, 15], [16, 17, 18],[19, 20, 21]]])
print(array_7)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]]]


In [29]:
# ndim attribute

import numpy as np

a = np.array(94)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimeonsional Arrays

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


Access Array Elements

In [31]:
import numpy as np

In [32]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [33]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [34]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


Accessing 2-D Arrays

In [35]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd dim :' ,arr[1, 4])

5th element on 2nd dim : 10


In [37]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Negative Indexing

In [38]:
import numpy as np