Youtube Channel : Hasan Çağrı Güngör 

https://youtube.com/playlist?list=PL3ED48mWmYxraLfbHEn4Xjii3mBilFIka&si=s-ZMvuxKqSyBc5T_

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

2- Numpy: Point, Line, Plane, and Space

In [3]:
scalar = np.array(90)
print(scalar)

90


In [4]:
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector)

[1 2 3 4 5 6]


In [5]:
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


3- ) Why Do We Use NumPy ?

SIMD Programming = Single Instruction Multiple Data
Numpy is a library for the Python programming language,
adding support for large, multi-dimensional arrays and matrices, 
along with a large collection of high-level mathematical functions to operate on these arrays.

In [7]:
import time

my_list = []

t1 = time.time()
for a in range(1_000_000):
    power = a ** 100
    my_list.append(power)
t2 = time.time()
print(t2 - t1)

0.6816310882568359


In [8]:
z3 = time.time()
my_list2 = np.arange(1_000_000) ** 100
z4 = time.time()
print(z4 - z3)

0.0028121471405029297


3- Indexing And Slicing In NumPy

In [9]:
vector = np.array([0,2,4,5,6,7,8,15])

In [10]:
vector[3]

np.int64(5)

In [11]:
vector[0]

np.int64(0)

In [12]:
vector[-1]

np.int64(15)

In [13]:
vector[1:3]

array([2, 4])

In [14]:
vector[:5]

array([0, 2, 4, 5, 6])

5-) Size, Shape, Dtype, ndim

In [15]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
print(vector)

[1 2 3 4 5 6]


In [17]:
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
vector.size

6

In [19]:
matrice.size

9

In [20]:
vector.shape

(6,)

In [21]:
matrice.shape

(3, 3)

In [22]:
vector.ndim

1

In [23]:
matrice.ndim

2

In [24]:
vector.dtype

dtype('int64')

In [25]:
matrice.dtype

dtype('int64')

6-) Changing Data Type In NumPy

In [26]:
numbers = np.array([1, 2, 3, 4, 5, 6])
numbers.dtype

dtype('int64')

In [27]:
numbers = np.array([1, 2.0, 3, 4, 5, 6])
numbers.dtype

dtype('float64')

In [28]:
numbers = numbers.astype("int32")
numbers.dtype

dtype('int32')

In [29]:
numbers = np.array([1, 2, 3, 4, 5, 6], dtype="int8")
numbers.dtype

dtype('int8')

In [30]:
date = np.array("2024-06-01")
date.dtype

dtype('<U10')

In [31]:
date = date.astype("datetime64[ns]")
date.dtype

dtype('<M8[ns]')

7 -) Slicing In Matrices

In [32]:
matrice = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [33]:
matrice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
matrice[0]

array([1, 2, 3, 4])

In [35]:
matrice[1]

array([5, 6, 7, 8])

In [36]:
matrice[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
matrice[0,:]

array([1, 2, 3, 4])

In [38]:
matrice[0,:2]

array([1, 2])

In [39]:
matrice[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

Making Random Matrice 

In [40]:
np.random.randint(0,5)

4

In [41]:
np.random.randint(0,5, size=(5,5))

array([[2, 3, 0, 0, 4],
       [0, 3, 0, 1, 4],
       [1, 2, 4, 3, 0],
       [3, 3, 0, 4, 2],
       [2, 4, 4, 4, 3]])

In [42]:
np.random.randint(0,10,(4,4))/10

array([[0.2, 0.5, 0.7, 0.1],
       [0.1, 0.5, 0.5, 0.5],
       [0.2, 0.1, 0.4, 0.3],
       [0.4, 0.2, 0.1, 0.3]])

Making Vectors with arange()

In [43]:
list_1 = [1,2,3,4,5,6]
range(1000000)

range(0, 1000000)

In [44]:
million = np.arange(1000000)

In [45]:
million

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [48]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

Making Vector with linspace()

In [49]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [50]:
divide = np.linspace(5,25,15)

In [51]:
divide[5]-divide[4]

np.float64(1.428571428571427)

Resizing with reshape()

In [52]:
m1 = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10], [10,11,12,13], [14,15,16,17], [18,19,20,21], [22,23,24,25]])

In [53]:
m1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [54]:
m1.shape

(7, 4)

In [55]:
m1.size

28

In [56]:
m1.reshape(2,14)

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [57]:
m1.reshape(4,7)

array([[ 1,  2,  3,  4,  4,  5,  6],
       [ 7,  7,  8,  9, 10, 10, 11],
       [12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

In [58]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
np.linspace(0,20,24).reshape(4,6)

array([[ 0.        ,  0.86956522,  1.73913043,  2.60869565,  3.47826087,
         4.34782609],
       [ 5.2173913 ,  6.08695652,  6.95652174,  7.82608696,  8.69565217,
         9.56521739],
       [10.43478261, 11.30434783, 12.17391304, 13.04347826, 13.91304348,
        14.7826087 ],
       [15.65217391, 16.52173913, 17.39130435, 18.26086957, 19.13043478,
        20.        ]])

copy() / view() methods in NumPy

In [60]:
matrice = np.random.randint(0,5,(4,4))

In [61]:
matrice

array([[3, 3, 0, 4],
       [3, 2, 2, 3],
       [0, 0, 2, 3],
       [0, 1, 4, 2]])

In [62]:
matrice2 = matrice.view()

In [63]:
matrice2[0]

array([3, 3, 0, 4])

In [64]:
matrice2[0] = [0,0,0,0]

In [65]:
matrice

array([[0, 0, 0, 0],
       [3, 2, 2, 3],
       [0, 0, 2, 3],
       [0, 1, 4, 2]])

In [66]:
matrice3 = np.random.randint(0,5,(4,4))

In [67]:
matrice3

array([[2, 2, 0, 0],
       [2, 0, 1, 3],
       [1, 3, 0, 4],
       [1, 4, 4, 2]])

In [68]:
matrice4 = matrice3.copy()

In [69]:
matrice4

array([[2, 2, 0, 0],
       [2, 0, 1, 3],
       [1, 3, 0, 4],
       [1, 4, 4, 2]])

In [70]:
matrice4[0] = [0,0,0,0]

In [71]:
matrice3

array([[2, 2, 0, 0],
       [2, 0, 1, 3],
       [1, 3, 0, 4],
       [1, 4, 4, 2]])

Methods of Creating Matrice -> ones(), zeros(), full()

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.ones(4)

array([1., 1., 1., 1.])

In [77]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

NumPy methods -> eye(), diag(), identity()

In [79]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [82]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [84]:
r = np.random.randint(0,3,(5,5))
print(r)

[[0 0 0 0 0]
 [2 0 0 1 2]
 [1 2 2 2 1]
 [1 0 0 1 0]
 [0 0 2 1 0]]


In [85]:
np.diag(r)

array([0, 0, 2, 1, 0])

In [86]:
np.diag(np.diag(r))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

Math Operations in Matrices ( Addition - Subtraction - Multiplication - Division )

In [87]:
m1 = np.ones((5,5))
m2 = np.full((5,5),19)

In [88]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [90]:
m1 = m1.astype("int16")

In [91]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [92]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [93]:
m1 * 4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int16)

In [94]:
m2 + 3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [95]:
m2 + m1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [96]:
m2 - m1

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

In [97]:
m2 / 3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [98]:
m2 // 3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [99]:
m2 % 3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [100]:
m3 = np.full((5,6),2)

In [101]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [102]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [103]:
m3.shape

(5, 6)

In [104]:
m2.shape

(5, 5)

In [105]:
# m2 + m3 
# they cannot be added together because they have different shapes.

In [106]:
m3.reshape(30)[:25].reshape(5,5) + m2

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [107]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [108]:
m1[0] = m1[0] * 3

In [109]:
m1

array([[3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [110]:
m5 = np.arange(5).reshape(5,1)

In [111]:
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [112]:
m1 * m5 

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [113]:
m1 / m5

/var/folders/k3/0k_nwjls3pzcz274xcvzy6pc0000gn/T/ipykernel_30364/4178138851.py:1: RuntimeWarning: divide by zero encountered in divide
  m1 / m5


array([[       inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ]])

In [114]:
m6 = m1 + m5 

In [115]:
m6

array([[3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [116]:
m6 * np.diag(m6)

array([[ 9,  6,  9, 12, 15],
       [ 6,  4,  6,  8, 10],
       [ 9,  6,  9, 12, 15],
       [12,  8, 12, 16, 20],
       [15, 10, 15, 20, 25]])

Logical Operators and Filtering with NumPy

In [117]:
matrice = np.random.randint(0,10,(5,5))

In [118]:
matrice

array([[9, 1, 9, 2, 5],
       [1, 6, 9, 4, 4],
       [1, 8, 5, 0, 2],
       [1, 1, 9, 5, 0],
       [3, 8, 6, 7, 2]])

In [119]:
matrice > 5

array([[ True, False,  True, False, False],
       [False,  True,  True, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True, False]])

In [120]:
matrice[matrice > 5]

array([9, 9, 6, 9, 8, 9, 8, 6, 7])

In [121]:
matrice[matrice < 5]

array([1, 2, 1, 4, 4, 1, 0, 2, 1, 1, 0, 3, 2])

In [122]:
matrice[matrice == 5]

array([5, 5, 5])

In [123]:
matrice[matrice == 7].size

1

In [124]:
matrice[matrice % 2 == 0]

array([2, 6, 4, 4, 8, 0, 2, 0, 8, 6, 2])

In [125]:
zero = matrice == 0
even = matrice % 2 == 0

In [126]:
matrice[even]

array([2, 6, 4, 4, 8, 0, 2, 0, 8, 6, 2])

In [127]:
zero = matrice != 0
one = matrice == 1
even = matrice % 2 == 0

In [128]:
matrice[even & zero]

array([2, 6, 4, 4, 8, 2, 8, 6, 2])

In [129]:
matrice[even | one]

array([1, 2, 1, 6, 4, 4, 1, 8, 0, 2, 1, 1, 0, 8, 6, 2])

In [130]:
matrice[(even & zero) | one]

array([1, 2, 1, 6, 4, 4, 1, 8, 2, 1, 1, 8, 6, 2])

In [131]:
matrice.shape

(5, 5)

In [132]:
m2 = np.full((5,5),5)

In [133]:
m2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [134]:
m2[(even & zero) | one]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

The End...