Youtube Channel : Hasan Çağrı Güngör 

https://youtube.com/playlist?list=PL3ED48mWmYxraLfbHEn4Xjii3mBilFIka&si=s-ZMvuxKqSyBc5T_

In [606]:
import numpy as np

In [607]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

2- Numpy: Point, Line, Plane, and Space

In [608]:
scalar = np.array(90)
print(scalar)

90


In [609]:
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector)

[1 2 3 4 5 6]


In [610]:
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [611]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


3- ) Why Do We Use NumPy ?

SIMD Programming = Single Instruction Multiple Data
Numpy is a library for the Python programming language,
adding support for large, multi-dimensional arrays and matrices, 
along with a large collection of high-level mathematical functions to operate on these arrays.

In [612]:
import time

my_list = []

t1 = time.time()
for a in range(1_000_000):
    power = a ** 100
    my_list.append(power)
t2 = time.time()
print(t2 - t1)

0.6484031677246094


In [613]:
z3 = time.time()
my_list2 = np.arange(1_000_000) ** 100
z4 = time.time()
print(z4 - z3)

0.0033431053161621094


3- Indexing And Slicing In NumPy

In [614]:
vector = np.array([0,2,4,5,6,7,8,15])

In [615]:
vector[3]

np.int64(5)

In [616]:
vector[0]

np.int64(0)

In [617]:
vector[-1]

np.int64(15)

In [618]:
vector[1:3]

array([2, 4])

In [619]:
vector[:5]

array([0, 2, 4, 5, 6])

5-) Size, Shape, Dtype, ndim

In [620]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [621]:
print(vector)

[1 2 3 4 5 6]


In [622]:
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [623]:
vector.size

6

In [624]:
matrice.size

9

In [625]:
vector.shape

(6,)

In [626]:
matrice.shape

(3, 3)

In [627]:
vector.ndim

1

In [628]:
matrice.ndim

2

In [629]:
vector.dtype

dtype('int64')

In [630]:
matrice.dtype

dtype('int64')

6-) Changing Data Type In NumPy

In [631]:
numbers = np.array([1, 2, 3, 4, 5, 6])
numbers.dtype

dtype('int64')

In [632]:
numbers = np.array([1, 2.0, 3, 4, 5, 6])
numbers.dtype

dtype('float64')

In [633]:
numbers = numbers.astype("int32")
numbers.dtype

dtype('int32')

In [634]:
numbers = np.array([1, 2, 3, 4, 5, 6], dtype="int8")
numbers.dtype

dtype('int8')

In [635]:
date = np.array("2024-06-01")
date.dtype

dtype('<U10')

In [636]:
date = date.astype("datetime64[ns]")
date.dtype

dtype('<M8[ns]')

7 -) Slicing In Matrices

In [637]:
matrice = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [638]:
matrice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [639]:
matrice[0]

array([1, 2, 3, 4])

In [640]:
matrice[1]

array([5, 6, 7, 8])

In [641]:
matrice[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [642]:
matrice[0,:]

array([1, 2, 3, 4])

In [643]:
matrice[0,:2]

array([1, 2])

In [644]:
matrice[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

Making Random Matrice 

In [645]:
np.random.randint(0,5)

0

In [646]:
np.random.randint(0,5, size=(5,5))

array([[3, 4, 1, 2, 4],
       [2, 2, 3, 4, 3],
       [3, 2, 2, 4, 4],
       [4, 4, 3, 1, 3],
       [2, 3, 3, 1, 1]])

In [647]:
np.random.randint(0,10,(4,4))/10

array([[0.7, 0.7, 0.5, 0.6],
       [0.3, 0.2, 0. , 0.3],
       [0.4, 0.1, 0.6, 0.5],
       [0.9, 0.1, 0.6, 0.5]])

Making Vectors with arange()

In [648]:
list_1 = [1,2,3,4,5,6]
range(1000000)

range(0, 1000000)

In [649]:
million = np.arange(1000000)

In [650]:
million

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [651]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [652]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [653]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

Making Vector with linspace()

In [654]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [655]:
divide = np.linspace(5,25,15)

In [656]:
divide[5]-divide[4]

np.float64(1.428571428571427)

Resizing with reshape()

In [657]:
m1 = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10], [10,11,12,13], [14,15,16,17], [18,19,20,21], [22,23,24,25]])

In [658]:
m1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [659]:
m1.shape

(7, 4)

In [660]:
m1.size

28

In [661]:
m1.reshape(2,14)

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [662]:
m1.reshape(4,7)

array([[ 1,  2,  3,  4,  4,  5,  6],
       [ 7,  7,  8,  9, 10, 10, 11],
       [12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

In [663]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0]])

In [664]:
np.linspace(0,20,24).reshape(4,6)

array([[ 0.        ,  0.86956522,  1.73913043,  2.60869565,  3.47826087,
         4.34782609],
       [ 5.2173913 ,  6.08695652,  6.95652174,  7.82608696,  8.69565217,
         9.56521739],
       [10.43478261, 11.30434783, 12.17391304, 13.04347826, 13.91304348,
        14.7826087 ],
       [15.65217391, 16.52173913, 17.39130435, 18.26086957, 19.13043478,
        20.        ]])

copy() / view() methods in NumPy

In [665]:
matrice = np.random.randint(0,5,(4,4))

In [666]:
matrice

array([[2, 1, 4, 2],
       [4, 4, 1, 1],
       [1, 2, 1, 2],
       [1, 1, 3, 4]])

In [667]:
matrice2 = matrice.view()

In [668]:
matrice2[0]

array([2, 1, 4, 2])

In [669]:
matrice2[0] = [0,0,0,0]

In [670]:
matrice

array([[0, 0, 0, 0],
       [4, 4, 1, 1],
       [1, 2, 1, 2],
       [1, 1, 3, 4]])

In [671]:
matrice3 = np.random.randint(0,5,(4,4))

In [672]:
matrice3

array([[0, 3, 1, 1],
       [3, 2, 0, 3],
       [4, 4, 4, 4],
       [1, 4, 4, 3]])

In [673]:
matrice4 = matrice3.copy()

In [674]:
matrice4

array([[0, 3, 1, 1],
       [3, 2, 0, 3],
       [4, 4, 4, 4],
       [1, 4, 4, 3]])

In [675]:
matrice4[0] = [0,0,0,0]

In [676]:
matrice3

array([[0, 3, 1, 1],
       [3, 2, 0, 3],
       [4, 4, 4, 4],
       [1, 4, 4, 3]])

Methods of Creating Matrice -> ones(), zeros(), full()

In [677]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [678]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [679]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [680]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [681]:
np.ones(4)

array([1., 1., 1., 1.])

In [682]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [683]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

NumPy methods -> eye(), diag(), identity()

In [684]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [685]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [686]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [687]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [688]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [689]:
r = np.random.randint(0,3,(5,5))
print(r)

[[1 1 1 0 2]
 [0 2 2 1 0]
 [0 2 0 1 2]
 [1 1 2 1 0]
 [0 0 0 0 1]]


In [690]:
np.diag(r)

array([1, 2, 0, 1, 1])

In [691]:
np.diag(np.diag(r))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Math Operations in Matrices ( Addition - Subtraction - Multiplication - Division )

In [692]:
m1 = np.ones((5,5))
m2 = np.full((5,5),19)

In [693]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [694]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [695]:
m1 = m1.astype("int16")

In [696]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [697]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [698]:
m1 * 4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int16)

In [699]:
m2 + 3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [700]:
m2 + m1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [701]:
m2 - m1

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

In [702]:
m2 / 3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [703]:
m2 // 3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [704]:
m2 % 3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [705]:
m3 = np.full((5,6),2)

In [706]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [707]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [708]:
m3.shape

(5, 6)

In [709]:
m2.shape

(5, 5)

In [710]:
# m2 + m3 
# they cannot be added together because they have different shapes.

In [711]:
m3.reshape(30)[:25].reshape(5,5) + m2

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [712]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [713]:
m1[0] = m1[0] * 3

In [714]:
m1

array([[3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)