In [80]:
import numpy as np

In [81]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

2- Numpy: Point, Line, Plane, and Space

In [82]:
scalar = np.array(90)
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [83]:
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector)

[1 2 3 4 5 6]


In [84]:
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


3- ) Why Do We Use NumPy ?

SIMD Programming = Single Instruction Multiple Data
Numpy is a library for the Python programming language,
adding support for large, multi-dimensional arrays and matrices, 
along with a large collection of high-level mathematical functions to operate on these arrays.

In [86]:
import time

my_list = []

t1 = time.time()
for a in range(1_000_000):
    power = a ** 100
    my_list.append(power)
t2 = time.time()
print(t2 - t1)

0.6374390125274658


In [87]:
z3 = time.time()
my_list2 = np.arange(1_000_000) ** 100
z4 = time.time()
print(z4 - z3)

0.002507925033569336


3- Indexing And Slicing In NumPy

In [88]:
vector = np.array([0,2,4,5,6,7,8,15])

In [89]:
vector[3]

np.int64(5)

In [90]:
vector[0]

np.int64(0)

In [91]:
vector[-1]

np.int64(15)

In [92]:
vector[1:3]

array([2, 4])

In [93]:
vector[:5]

array([0, 2, 4, 5, 6])

5-) Size, Shape, Dtype, ndim

In [94]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [95]:
print(vector)

[1 2 3 4 5 6]


In [96]:
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
vector.size

6

In [98]:
matrice.size

9

In [99]:
vector.shape

(6,)

In [100]:
matrice.shape

(3, 3)

In [101]:
vector.ndim

1

In [102]:
matrice.ndim

2

In [103]:
vector.dtype

dtype('int64')

In [104]:
matrice.dtype

dtype('int64')

6-) Changing Data Type In NumPy

In [105]:
numbers = np.array([1, 2, 3, 4, 5, 6])
numbers.dtype

dtype('int64')

In [106]:
numbers = np.array([1, 2.0, 3, 4, 5, 6])
numbers.dtype

dtype('float64')

In [107]:
numbers = numbers.astype("int32")
numbers.dtype

dtype('int32')

In [108]:
numbers = np.array([1, 2, 3, 4, 5, 6], dtype="int8")
numbers.dtype

dtype('int8')

In [109]:
date = np.array("2024-06-01")
date.dtype

dtype('<U10')

In [112]:
date = date.astype("datetime64[ns]")
date.dtype

dtype('<M8[ns]')

7 -) Slicing In Matrices